#pragma once
#include "CBillboardRender.h"
#include "CCamera.h"
#include "CCollider2D.h"
// #include "CCollider3D.h"
#include "CFlipbookRender.h"
#include "CLight2D.h"
// #include "CLight3D.h"
#include "CMeshRender.h"
// #include "CParticleRender.h"
#include "CSpriteRender.h"
#include "CRigidBody.h"
#include "CTileRender.h"
#include "CTransform.h"
// #include "CRigidbody.h"
// #include "CNone.h"
// #include "CEBillboardrender.h"
// #include "CECamera.h"
// #include "CECollider2D.h"
// #include "CECollider3D.h"
// #include "CEFlipbookrender.h"
// #include "CELight2D.h"
// #include "CELight3D.h"
// #include "CEMeshrender.h"
// #include "CENone.h"
// #include "CEParticlerender.h"
// #include "CERigidbody.h"
// #include "CESpriterender.h"
// #include "CETilerender.h"
// #include "CETransform.h"
#include "CScript.h"